### ISSUE TITLE
gumbelinv is incorrect

### ISSUE THREAD

**Issue by nir-krakauer** [gnu-octave/statistics#145]
Because of a misplaced minus sign, the value returned by the current gumbelinv function is incorrect. Attached patch fixes it and adds a test for correctness.
[gumbelinv_diff.txt](https://github.com/gnu-octave/statistics/files/15142619/gumbelinv_diff.txt)

**Comment by pr0m1th3as** [comment]
@nir-krakauer I am traveling once again during this week. Could you make a PR so I can merge it from my mobile phone, please?

**Comment by nir-krakauer** [comment]
Like this? https://github.com/nir-krakauer/statistics/pull/1

**Comment by pr0m1th3as** [comment]
I cannot merge the PR to your own personal clone of the statistics repo. Merge your PR there and then make a PR to the `/gnu-octave/statistics` repo so I can merge it.

**Comment by pr0m1th3as** [comment]
The PR has been merged. Thanks! Closing this issue
