### ISSUE TITLE
Error in Creating KNN classifier with explicit ClassNames

### ISSUE THREAD

**Issue by ruchikasonagote** [gnu-octave/statistics#148]
I encountered an error while attempting to create a K-Nearest Neighbor classifier using the Iris dataset. The error message indicates a problem with the 'N' parameter, specifically:
![image](https://github.com/gnu-octave/statistics/assets/111609654/23c6bc19-63be-4d1c-b8e6-f0c4d0a8c15b)

Code Snippet:
```bash
load fisheriris
X = meas;
Y = species;
ClassNames = {'setosa', 'versicolor', 'virginica'};
Mdl = fitcknn (X, Y, 'ClassNames', ClassNames);
```
Expected Behavior:
The `fitcknn` function should create a KNN classifier object.

**Comment by dasergatskov** [comment]
I do not understand what the code does, but `ac = find (gnY, ClassNames{i})` looks wrong, perhaps it should be
`ac = find (strcmp(gnY, ClassNames{i}))` ?

**Comment by pr0m1th3as** [comment]
Thanks @dasergatskov for pointing this out. I included the above code snippet as a unit test.
