### ISSUE TITLE
No documentation in release tarball for 1.7.0

### ISSUE THREAD

**Issue by svillemot** [gnu-octave/statistics#159]
The release tarball for version 1.7.0 no longer contains the documentation (which was present in previous tarballs).

Was this done on purpose?

We currently ship the documentation in the Debian package, based on what’s inside the tarball.

**Comment by svillemot** [comment]
cc @rlaboiss

**Comment by pr0m1th3as** [comment]
Yes, this is on purpose since version 1.6.7 to reduce the size of the tarball (thus the time to download) required for installation.

**Comment by svillemot** [comment]
Thanks for the clarification.

Is it possible to regenerate the HTML files from the source tarball?

**Comment by pr0m1th3as** [comment]
After installing and loading the statistics package, you can generate the html pages locally with the `pkg-octave-doc` package.


FYI, the release tarball is 1.3MB whereas the tarball containing the `/docs` folder grows to 7.8MB. When uncompressed, 8.5MB and 48.2MB, respectively.

**Comment by svillemot** [comment]
Thanks for the explanation. We’ll see whether we keep the generated docs in the Debian package.

**Comment by pr0m1th3as** [comment]
I have updated the [README.md](https://github.com/gnu-octave/statistics/blob/main/README.md) file to include information on how to build online documentation locally. Hopefully, this makes things a bit more straightforward for people who might need the documentation offline.
