### ISSUE TITLE
BISTs in ClassificationPartitionedModel can take forever

### ISSUE THREAD

**Issue by svillemot** [gnu-octave/statistics#160]
I uploaded `statistics` 1.7.0 to Debian and I get build failures related to BISTs in `ClassificationPartitionedModel` that take forever (at least more than 150 minutes). This seems to be a random issue. See for example this build log:
https://buildd.debian.org/status/fetch.php?pkg=octave-statistics&arch=amd64&ver=1.7.0-1&stamp=1725455778&raw=0

May this be related to the use of random data in the BISTs?

**Comment by pr0m1th3as** [comment]
This should not be a problem. The input validation tests in `ClassificationPartitionedModel` run really fast.
```
>> tic; fail ("ClassificationPartitionedModel (RegressionGAM (ones (40,2), randi ([1, 2], 40, 1)), cvpartition (randi ([1, 2], 40, 1), 'Holdout', 0.3))", "ClassificationPartitionedModel: unsupported model type.");toc
Elapsed time is 0.0237939 seconds.
>>
```
The output tests take some significant amount of time, but certainly not that long. On Ubuntu 20.04 with Octave 9.1, all tests pass.
```
>> t0 = clock (); test ClassificationPartitionedModel; etime (clock (), t0)
PASSES 19 out of 19 tests
ans = 30.369
>>
```
The only thing wrong I notice with `ClassificationPartitionedModel` is that I don't check/validate the input for the cvpartition object as the second argument.

**Comment by pr0m1th3as** [comment]
After last update, the testing time is still relatively small
```
>> t0 = clock (); test ClassificationPartitionedModel; etime (clock (), t0)
PASSES 20 out of 20 tests
ans = 33.782
```
I doubt, the issue you are facing on debian is related to the BISTs in `ClassificationPartinedModel` class. Or at least I cannot find a connection from the build log file you referenced.

**Comment by svillemot** [comment]
I assumed the problem comes from `ClassificationPartitionedModel` because the timeout message comes in the middle of the BISTs of that function. Of course the root cause could lie somewhere else, for example in Octave core.

**Comment by svillemot** [comment]
More precisely, repeatedly running the following is enough to reproduce the random issue:
```
RegressionGAM (ones (40,2), randi ([1, 2], 40, 1))
```

**Comment by svillemot** [comment]
Debugging shows that the `fitsGAM` method of the `RegressionGAM` enters an infinite loop. For some reason, the regression never converges on some random data and with Netlib BLAS/LAPACK.

**Comment by pr0m1th3as** [comment]
@svillemot Can you check again with the latest commit?

**Comment by svillemot** [comment]
Thanks. Your fix doesn’t work because the logic is wrong (should be `iter < 1000`).

**Comment by pr0m1th3as** [comment]
My bad. Does it work now?

**Comment by svillemot** [comment]
The latest commit indeed fixes the issue, but I realize that it introduces another problem: there will always be at least 1000 iterations, even if convergence occurs before.

The test should rather be `while (!(converged || iter > 1000))` (note the parenthesis). Sorry for suggesting a wrong fix in my previous comment.

**Comment by pr0m1th3as** [comment]
Now it should be fixed

**Comment by svillemot** [comment]
Thanks, thus closing.
