### ISSUE TITLE
PoissonDistribution.plot("plottype","cdf") produces wrong index error 

### ISSUE THREAD

**Issue by ecky-l** [gnu-octave/statistics#162]
When trying to plot the CDF of a PoissonDistribution object, the length of the data is taken as a reference, however `cdfcalc` might produce `yCDF` and `xCDF` outputs of smaller length (when diff == 0 for certain data points in x). This results in an index error in the `__plot__` function.

I will create a pull request which fixes the issue. Code is mainly borrowed from `cdfplot`, where it is apparently correct.

**Comment by pr0m1th3as** [comment]
Thanks for pointing this out and for the PR as well. Closing as fixed
