### ISSUE TITLE
Error installing statistics

### ISSUE THREAD

**Issue by jonathanhhb** [gnu-octave/statistics#89]
Hello. Don't have much experience with octave. I'm using it to get some matlab code running. The classify is apparently from statistics package but I can't install successfully. Is this a bug or something I can fix in user land?

```
octave:1> pkg install "https://github.com/gnu-octave/statistics/archive/refs/tags/release-1.5.4.tar.gz"
warning: creating installation directory /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages
warning: called from
    install at line 36 column 5
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/std.m shadows a core library function
warning: called from
    /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/PKG_ADD at line 11 column 3
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/median.m shadows a core library function
warning: called from
    /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/PKG_ADD at line 11 column 3
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/mean.m shadows a core library function
warning: called from
    /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/PKG_ADD at line 11 column 3
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/var.m shadows a core library function
warning: called from
    /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/PKG_ADD at line 11 column 3
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/std.m shadows a core library function
warning: called from
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/median.m shadows a core library function
warning: called from
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/mean.m shadows a core library function
warning: called from
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: function /home/jbloedow/snap/octave/306/.local/share/octave/api-v57/packages/statistics-1.5.4/shadow9/var.m shadows a core library function
warning: called from
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

For information about changes from previous versions of the statistics package, run 'news statistics'.
octave:2> pkg load "https://github.com/gnu-octave/statistics/archive/refs/tags/release-1.5.4.tar.gz"
error: package https://github.com/gnu-octave/statistics/archive/refs/tags/release-1.5.4.tar.gz is not installed
error: called from
    load_packages at line 47 column 7
    pkg at line 623 column 7
octave:3>
```

**Comment by jonathanhhb** [comment]
![image](https://user-images.githubusercontent.com/13157334/232828719-72a69446-417b-4883-8f02-93787101d19c.png)

**Comment by pr0m1th3as** [comment]
You have installed the statistics package successfully. After installation, you just type
````
pkg load statistics
````
in order to load it. Note, you only need to install it once, but you need you load it every time you open Octave.

**Comment by jonathanhhb** [comment]
> You have installed the statistics package successfully. After installation, you just type
> 
> ```
> pkg load statistics
> ```
> 
> in order to load it. Note, you only need to install it once, but you need you load it every time you open Octave.

Thanks.

![image](https://user-images.githubusercontent.com/13157334/232867688-5286db47-0db4-4d0b-b619-6f472487d059.png)

What am I missing?

**Comment by jonathanhhb** [comment]
> > You have installed the statistics package successfully. After installation, you just type
> > ```
> > pkg load statistics
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in order to load it. Note, you only need to install it once, but you need you load it every time you open Octave.
> 
> Thanks.
> 
> ![image](https://user-images.githubusercontent.com/13157334/232867688-5286db47-0db4-4d0b-b619-6f472487d059.png)
> 
> What am I missing?

I realize I'm not passing any params to classify so it wouldn't work, but I expect an error about params, not telling me that the package isn't installed. 

I realize the warnings are "only" warnings, but they feel like errors based on the final "result".

**Comment by acp29** [comment]
My understanding is that you are receiving this error because the function called 'classify' has not been coded (yet) in the Octave Statistics package. You don't get an error about function parameters because the function does not exist. 

The warnings are simply because the statistics package has newer, more Matlab compatible versions of some functions, specifically mean, var, std, median. I imagine that in future versions, these warnings will disappear as the new functions will be moved to Octave core.


——
 
Dr Andrew Penn (he/his)
Sussex Neuroscience
School of Life Sciences
University of Sussex
Brighton BN1 9QG
United Kingdom
 
Tel: +44 (0)1273 877049
E-mail: ***@***.***
 
http://www.sussex.ac.uk/lifesci/pennlab/
http://www.researchgate.net/profile/Andrew_Penn
https://scholar.google.com/citations?user=pDxdZaoAAAAJ&hl=en
http://sussex.academia.edu/AndrewPenn

**Comment by jonathanhhb** [comment]
ChatGPT says:
```
pkg load statistics

# Create a svm Classifier
clf = fitcsvm(X_train, y_train, 'KernelFunction', 'linear');

# Predict the response for test dataset
y_pred = predict(clf, X_test);
```

**Comment by pr0m1th3as** [comment]
SVM in the statistics package is supported through the `libsvm` library. The functions available are [`svmtrain`](https://gnu-octave.github.io/statistics/svmtrain.html) and [`svmpredict`](https://gnu-octave.github.io/statistics/svmpredict.html).

**Comment by jonathanhhb** [comment]
> SVM in the statistics package is supported through the `libsvm` library. The functions available are [`svmtrain`](https://gnu-octave.github.io/statistics/svmtrain.html) and [`svmpredict`](https://gnu-octave.github.io/statistics/svmpredict.html).

Awesome. That seems to be what I need. Please feel free to close the ticket as resolved. Appreciate your software and your support.
