### ISSUE TITLE
Release 1.5.4: PCA crashes with a single output when the number of components is specified

### ISSUE THREAD

**Issue by tiborauer** [gnu-octave/statistics#97]
The error occurs when the condition in https://github.com/gnu-octave/statistics/blob/8a8e723c32b6d9a87f2da993284c97159ef6061d/inst/pca.m#L367 is not met but the condition in https://github.com/gnu-octave/statistics/blob/8a8e723c32b6d9a87f2da993284c97159ef6061d/inst/pca.m#L449 is.

**Comment by pr0m1th3as** [comment]
Could you provide an example?

**Comment by tiborauer** [comment]
`comp = pca(rand(10,100),'NumComponents',2)`

**Comment by pr0m1th3as** [comment]
Just pushed a commit that fixes this error!

**Comment by tiborauer** [comment]
Thank you! Would you also update the Octave package?
